### ISSUE TITLE
Compiling for Windows

### ISSUE THREAD

**Issue by aDramaQueen** [berkeley-abc/abc#128]
Hello,
i noticed in your Troubleshooting section, that you're offering some Windows DLLs. So I'm assuming you can compile ABC to a Windows apllication. Question is: How? I managed to compile the library in MinGW but for the executable your linking to **librt**. This is specific POSIX (https://docs.oracle.com/cd/E86824_01/html/E54772/librt-3lib.html) and as far, as I know there is no equivalent out there that I can use to replace **librt**...
I'm using MinGW32 under MSYS2. This is the result after sucessfull compiling the library:

```
SimpleJack@SimpleJacksPC MINGW32 ~/abc-master/build
$ make
[100%] Built target libabc
[100%] Linking CXX executable abc.exe
D:/Tools/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/10.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lrt
collect2.exe: error: ld returned 1 exit status
make[2]: *** [CMakeFiles\abc.dir\build.make:100: abc.exe] Error 1
make[1]: *** [CMakeFiles\Makefile2:110: CMakeFiles/abc.dir/all] Error 2
make: *** [Makefile:90: all] Error 2
```

**Comment by sterin** [comment]
Hi,

On Windows we build using Visual Studio 97 (it is kinda hard to explain why) project files rather than using the Makefile. 

Take a look at https://github.com/berkeley-abc/abc/blob/master/.appveyor.yml to find out how we build ABC for Windows on each git push. It basically converts the project files to modern Visual Studio project files and builds using Visual Studio. 

You can find the artifacts of the latest build at: https://ci.appveyor.com/project/berkeley-abc/abc/build/artifacts

Hope this helps,
Baruch
